=== alissa-huskey/blueprint/schemas/base.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "base.schema.json",
  "title": "Blueprint base schema",
  "description": "Schema for a project blueprint.",
  "version": "0.1.0",
  "type": "object",
  "$defs": {
    "constraint-nonEmptyString": {
      "$anchor": "nonEmptyString",
      "type": "string",
      "minLength": 1
    },
    "executable-outfile": {
      "$anchor": "Outfile",
      "description": "Output filename.",
      "$ref": "#nonEmptyString"
    },
    "executable-options": {
        "$anchor": "Options",
        "description": "Optional arguments to add to command or script only if variable in property name is defined",
        "examples": [ { "{SUMMARY}": ["--description", "{SUMMARY}"] } ],
        "type": "object",
        "minProperties": 1,
        "propertyNames": { "pattern": "^[$]\\{[A-Z_]+\\}$" },
        "additionalProperties": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        }
    },
    "executable-command": {
      "description": "Shell command.",
      "$anchor": "Command",
      "type": "object",
      "required": ["cmd"],
      "properties": {
        "cmd": {
          "description": "Command to execute.",
          "examples": [ ["git", "init"] ],
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "options": { "$ref": "#Options" },
        "outfile": { "$ref": "#Outfile" }
      }
    },
    "executable-script": {
      "description": "Script to run.",
      "examples": [[
        { "script": "setup-pyproject", "arguments": ["{VERSION}", "{PYV_CONSTRAINT}"] }
      ]],
      "$anchor": "Script",
      "type": "object",
      "required": ["script"],
      "properties": {
        "script": {
          "description": "Script to execute located in `scripts/` directory",
          "examples": ["bootstrap.sh"],
          "$ref": "#nonEmptyString"
        },
        "arguments": {
          "description": "Arguments to send to script",
          "examples": [
            ["{PATH}", "{VERSION}"],
            ["{CONFIG_ROOT}"]
          ],
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "options": { "$ref": "#Options" },
        "outfile": { "$ref": "#Outfile" }
      }
    },
    "executable": {
      "description": "Something to execute on the command line.",
      "$anchor": "Executable",
      "oneOf": [
        { "$ref": "#Command" },
        { "$ref": "#Script" }
      ]
    }
  },
  "required": ["name", "description", "version", "type"],
  "properties": {
    "name": {
      "description": "The unique identifier for this Project Type.",
      "examples": ["python-poetry", "phpbb-ext"],
      "$ref": "#nonEmptyString"
    },
    "title": {
      "description": "Human readable title.",
      "examples": [
        "Python Poetry Project",
        "phpBB Extension"
      ],
      "$comment": "Annotation",
      "$ref": "#nonEmptyString"
    },
    "description": {
      "description": "Brief description.",
      "examples": [
        "Python project managed by Poetry",
        "phpBB Extension"
      ],
      "$comment": "Annotation",
      "$ref": "#nonEmptyString"
    },
    "version": {
      "description": "Semantic version number.",
      "examples": ["0.1.0"],
      "$ref": "#nonEmptyString"
    },
    "type": {
      "description": "Type",
      "examples": ["language-toolstack"],
      "$ref": "#nonEmptyString",
      "enum": [
        "language-toolstack",
        "framework-application",
        "extension",
        "template",
        "tooling",
        "generic"
      ]
    },
    "parent": {
      "description": "Product Type to inherit from.",
      "examples": ["basic"],
      "$ref": "#nonEmptyString"
    },
    "project-dir": {
      "description": "Pattern of what to name the base project directory.",
      "examples": ["phpbb-${NAME}"],
      "$ref": "#nonEmptyString"
    },
    "requirements": {
      "description": "Requirements that must be installed on system to work.",
      "examples": [
        ["php", "composer"],
        ["python", "poetry", "asdf"]
      ],
      "type": "array",
      "uniqueItems": true,
      "items": { "$ref": "#nonEmptyString" }
    },
    "variables": {
      "description": "Variables to define.",
      "examples": [
        { "PYTHON_EXE": { "cmd": ["asdf", "where", "python", "{PYV}"] } }
      ],
      "type": "object",
      "additionalProperties": { "$ref": "#Executable" }
    },
    "options": {
      "description": "Additional command-line options a project can define.",
      "$comment": "Click Options params.",
      "examples": [
        [ { "pyv": { "default": "3.10.2", "help": "Python version" } } ]
      ],
      "type": "object",
      "properties": {
        "choices": {
          "description": "Allowed values.",
          "examples": [ [ "yes", "no" ]],
          "type": "array",
          "minItems": 2,
          "uniqueItems": true,
          "items": { "$ref": "#nonEmptyString" }
        }
      }
    },
    "arguments": {
      "description": "Arguments to use in addition to `name`. Keys are argument names, values are click.Argument kwargs.",
      "comment": "The name argument can be included for argument order. Otherwise, arguments are listed after `name`.",
      "examples": [{ "vendor": {}, "name": {} }],
      "type": "object"
    },
    "setup": {
      "description": "Steps to set up this project.",
      "examples": [[
        { "cmd": ["git", "init"] },
        { "script": "bootstrap.sh" },
        {
          "cmd": ["echo", "{PYV}"],
          "out": ".python-version"
        }
      ]],
      "type": "array",
      "items": { "$ref": "#Executable" }
    },
    "after": {
      "description": "Steps to take after skeleton has been installed.",
      "examples": [
        {
          "cmd": [
            "cp",
            "{TYPE_ROOT}/after/CodeSniffer.conf",
            "vendor/squizlabs/php_codesniffer/"
          ]
        }
      ],
      "type": "array",
      "items": { "$ref": "#Executable" }
    }
  }
}

=== alissa-huskey/blueprint/plans/phpbb-ext/blueprint.json
{
  "name": "phpbb-ext",
  "title": "phpBB Extension",
  "description": "phpBB Extension",
  "version": "0.1.0",
  "type": "extension",
  "parent": "php-composer",
  "project-dir": "phpbb-{{ DASH_NAME }}",
  "options": {
    "phpv": {
      "default": "7.4.33",
      "help": "PHP Version",
      "hidden": true
    },
    "php-constraint": {
      "default": ">=7.3",
      "help": "PHP Version Constraint",
      "hidden": true
    },
    "project-type": { 
      "default": "phpbb-extension",
      "help": "Composer project type",
      "hidden": true
    }
  }
}
