=== alissa-huskey/blueprint/docs/blueprint.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Project Type",
  "description": "Blueprint Project Type definition.",
  "version": "0.1.0",
  "type": "object",
  "$defs": {
    "constraint-nonEmptyString": {
      "$anchor": "nonEmptyString",
      "type": "string",
      "minLength": 1
    },
    "executable-outfile": {
      "$anchor": "Outfile",
      "description": "Output filename.",
      "$ref": "#nonEmptyString"
    },
    "executable-options": {
        "$anchor": "Options",
        "description": "Optional arguments to add to command or script only if variable in property name is defined",
        "examples": [ { "{SUMMARY}": ["--description", "{SUMMARY}"] } ],
        "type": "object",
        "minProperties": 1,
        "propertyNames": { "pattern": "^[$]\\{[A-Z_]+\\}$" },
        "additionalProperties": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        }
    },
    "executable-command": {
      "description": "Shell command.",
      "$anchor": "Command",
      "type": "object",
      "required": ["cmd"],
      "properties": {
        "cmd": {
          "description": "Command to execute.",
          "examples": [ ["git", "init"] ],
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "options": { "$ref": "#Options" },
        "outfile": { "$ref": "#Outfile" }
      }
    },
    "executable-script": {
      "description": "Script to run.",
      "examples": [[
        { "script": "setup-pyproject", "arguments": ["{VERSION}", "{PYV_CONSTRAINT}"] }
      ]],
      "$anchor": "Script",
      "type": "object",
      "required": ["script"],
      "properties": {
        "script": {
          "description": "Script to execute located in `scripts/` directory",
          "examples": ["bootstrap.sh"],
          "$ref": "#nonEmptyString"
        },
        "arguments": {
          "description": "Arguments to send to script",
          "examples": [
            ["{PATH}", "{VERSION}"],
            ["{CONFIG_ROOT}"]
          ],
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "options": { "$ref": "#Options" },
        "outfile": { "$ref": "#Outfile" }
      }
    },
    "executable": {
      "description": "Something to execute on the command line.",
      "$anchor": "Executable",
      "oneOf": [
        { "$ref": "#Command" },
        { "$ref": "#Script" }
      ]
    }
  },
  "required": ["name", "description", "version", "type"],
  "properties": {
    "name": {
      "description": "The unique identifier for this Project Type.",
      "examples": ["python-poetry", "phpbb-ext"],
      "$ref": "#nonEmptyString"
    },
    "title": {
      "description": "Human readable title.",
      "examples": [
        "Python Poetry Project",
        "phpBB Extension"
      ],
      "$comment": "Annotation",
      "$ref": "#nonEmptyString"
    },
    "description": {
      "description": "Brief description.",
      "examples": [
        "Python project managed by Poetry",
        "phpBB Extension"
      ],
      "$comment": "Annotation",
      "$ref": "#nonEmptyString"
    },
    "version": {
      "description": "Semantic version number.",
      "examples": ["0.1.0"],
      "$ref": "#nonEmptyString"
    },
    "type": {
      "description": "Type",
      "examples": ["language-toolstack"],
      "$ref": "#nonEmptyString",
      "enum": [
        "language-toolstack",
        "framework-application",
        "extension",
        "template",
        "tooling",
        "generic"
      ]
    },
    "parent": {
      "description": "Product Type to inherit from.",
      "examples": ["basic"],
      "$ref": "#nonEmptyString"
    },
    "requirements": {
      "description": "Requirements that must be installed on system to work.",
      "examples": [
        ["php", "composer"],
        ["python", "poetry", "asdf"]
      ],
      "type": "array",
      "uniqueItems": true,
      "items": { "$ref": "#nonEmptyString" }
    },
    "stack": {
      "description": "Toolstack specifications. (For type: language-toolstack)",
      "$comment": "Annotations",
      "type": "object",
      "additionalProperties": { "$ref": "#nonEmptyString" },
      "required": ["language"],
      "properties": {
        "language": {
          "description": "Primary language this project is written in.",
          "examples": ["python"],
          "$ref": "#nonEmptyString"
        },
        "dependencies": {
          "description": "Dependency management tool.",
          "examples": ["poetry"],
          "$ref": "#nonEmptyString"
        },
        "tests": {
          "description": "Testing framework.",
          "examples": ["pytest"],
          "$ref": "#nonEmptyString"
        },
        "linter": {
          "description": "Linter.",
          "examples": ["flake8"],
          "$ref": "#nonEmptyString"
        },
        "formatter": {
          "description": "Formatter",
          "examples": ["black"],
          "$ref": "#nonEmptyString"
        }
      }
    },
    "variables": {
      "description": "Variables to define.",
      "examples": [
        { "PYTHON_EXE": { "cmd": ["asdf", "where", "python", "{PYV}"] } }
      ],
      "type": "object",
      "additionalProperties": { "$ref": "#Executable" }
    },
    "options": {
      "description": "Additional command-line options a project can define.",
      "$comment": "Click Options params.",
      "examples": [
        [ { "pyv": { "default": "3.10.2", "help": "Python version" } } ]
      ],
      "type": "object",
      "properties": {
        "choices": {
          "description": "Allowed values.",
          "examples": [ [ "yes", "no" ]],
          "type": "array",
          "minItems": 2,
          "uniqueItems": true,
          "items": { "$ref": "#nonEmptyString" }
        }
      }
    },
    "setup": {
      "description": "Steps to set up this project.",
      "examples": [[
        { "cmd": ["git", "init"] },
        { "script": "bootstrap.sh" },
        {
          "cmd": ["echo", "{PYV}"],
          "out": ".python-version"
        }
      ]],
      "type": "array",
      "items": { "$ref": "#Executable" }
    },
    "after": {
      "description": "Steps to take after skeleton has been installed.",
      "examples": [
        {
          "cmd": [
            "cp",
            "{TYPE_ROOT}/after/CodeSniffer.conf",
            "vendor/squizlabs/php_codesniffer/"
          ]
        }
      ],
      "type": "array",
      "items": { "$ref": "#Executable" }
    },
    "dependency-commands": {
        "description": "Commands to add dependencies.",
        "examples": [
          {
            "main": ["poerty", "add"],
            "dev": ["poetry", "add", "--group", "dev"]
          }
        ],
        "type": "object",
        "properties": {
          "main": {
            "type": "array",
            "items": {"$rev": "#nonEmptyString"},
            "minItems": 1
          },
          "dev": {
            "type": "array",
            "items": {"$rev": "#nonEmptyString"},
            "minItems": 1
          }
        }
    }
  }
}

=== alissa-huskey/blueprint/plans/python-poetry/blueprint.json
{
  "name": "python-poetry",
  "title": "Python: Poetry",
  "description": "Python project managed by poetry.",
  "version": "0.1.0",
  "parent": "basic",
  "type": "language-toolstack",
  "stack": {
    "language": "python",
    "dependencies": "poetry",
    "tests": "pytest",
    "linter": "flake8",
    "formatter": "black"
  },
  "requirements": [ "python", "poetry", "asdf" ],
  "options": {
    "pyv": { 
      "default": "3.10.2",
      "metavar": "VERSION",
      "help": "Python version"
    },
    "pyv-constraint": { 
      "default": ">=3.10.2",
      "metavar": "CONSTRAINT",
      "help": "Python version constraint"
    }
  },
  "variables": {
    "PYTHON_EXE": { "cmd": ["asdf", "where", "python", "{{ PYV }}"] }
  },
  "setup": [
    {
      "cmd": ["echo", "{{ PYV }}"],
      "out": ".python-version"
    },
    {
      "cmd": [
        "poetry",
        "init",
        "--no-interaction",
        "--name", "{{ NAME | to_kebab_case }}",
        "--directory", "{{ PATH }}",
        "--python", "{{ PYV_CONSTRAINT }}"
      ],
      "options": {
        "{{ SUMMARY }}": ["--description", "{{ SUMMARY }}"],
        "{{ LICENSE }}": ["--license", "{{ LICENSE }}"]
      }
    },
    {
      "script": "setup-pyproject",
      "arguments": ["{{ PATH }}", "{{ VERSION }}", "{{ PYV_CONSTRAINT }}"]
    },
    { "cmd": ["poetry", "env", "use", "{{ PYTHON_EXE }}/bin/python"] },
    { "cmd": ["poetry", "install"] }
  ],
  "dependency-commands": {
    "main": ["poetry", "add"],
    "dev": ["poetry", "add", "--group", "dev"]
  }
}

=== alissa-huskey/blueprint/types/php-composer/blueprint.json
{
  "name": "php-composer",
  "description": "PHP project managed by Composer.",
  "version": "0.1.0",
  "type": "language-toolstack",
  "parent": "basic",
  "stack": {
    "language": "php",
    "dependencies": "composer",
    "tests": "phpunit",
    "linter": "phpcs"
  },
  "requirements": [ "php", "composer" ],
  "options": {
    "vendor": { 
      "required": true,
      "help": "Vendor.",
      "metavar": "VENDOR"
    },
    "phpv": {
      "default": "8.4",
      "help": "PHP Version",
      "metavar": "VERSION"
    },
    "php-constraint": {
      "default": ">=5",
      "help": "PHP Version Constraint",
      "metavar": "CONSTRAINT"
    },
    "project-type": { 
      "default": "project",
      "help": "Composer project type",
      "choices": [
        "library",
        "project",
        "metapackage",
        "composer-plugin"
      ]
    }
  },
  "setup": [
    { "cmd": ["composer", "install"] }
  ],
  "after": [
    {
      "cmd": [
        "cp",
        "{TYPE_ROOT}/after/CodeSniffer.conf",
        "vendor/squizlabs/php_codesniffer/"
      ]
    }
  ]
}

=== alissa-huskey/blueprint/plans/python-typer/blueprint.json
{
  "name": "python-typer",
  "title": "Python: Typer CLI App",
  "description": "A CLI application built on Typer.",
  "version": "0.1.0",
  "type": "framework-application",
  "parent": "python-poetry",
  "stack": {
    "language": "python",
    "dependencies": "poetry",
    "formatter": "black",
    "framework": "typer",
    "linter": "flake8",
    "tests": "pytest"
  }
}

=== alissa-huskey/blueprint/examples/design/blueprint.json
{
  "name": "design",
  "title": "Design",
  "parent": "basic",
  "description": "Graphic design projects.",
  "version": "0.1.0",
  "type": "generic",
  "requirements": ["git", "gh"],
  "options": {
    "software": {
      "help": "Graphic design software",
      "choices": [
        "illustrator",
        "inkscape",
        "sketchup",
        "fusion"
      ]
    }
  },
  "setup": [
    {
      "script": "setup-art-dir",
      "arguments": ["{{ PATH }}", "{{ SOFTWARE }}"]
    }
  ],
  "after": [
    { "cmd": ["git", "add", "."] },
    { "cmd": ["git", "commit", "-m", "Initial commit."] },
    { "cmd": ["gh", "repo", "create", "--public", "--push", "--source", "."] }
  ]
}
